<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Credentials</AssemblyName>
    <RootNamespace>mullvad.Module.Credentials</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>

  <!-- After build: copy to the server's Modules folder -->
  <Target Name="CopyToModules" AfterTargets="Build">
    <MakeDir
      Directories="..\..\mullvad\bin\$(Configuration)\net8.0-windows\Modules"
      ContinueOnError="true" />
    <Copy
      SourceFiles="$(OutputPath)$(AssemblyName).dll"
      DestinationFiles="..\..\mullvad\bin\$(Configuration)\net8.0-windows\Modules\mullvad.Module.Credentials.dll"
      SkipUnchangedFiles="true"
      ContinueOnError="true" />
  </Target>

</Project>
