<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mullvad.Protector.Core</RootNamespace>
    <AssemblyName>Mullvad.Protector.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.0.0" />
  </ItemGroup>

</Project>
