<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>InstalledApplications</AssemblyName>
    <RootNamespace>mullvad.Module.InstalledApplications</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <Target Name="CopyToModules" AfterTargets="Build">
    <MakeDir Directories="..\mullvad\bin\$(Configuration)\net8.0-windows\Modules" ContinueOnError="true" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
          DestinationFiles="..\mullvad\bin\$(Configuration)\net8.0-windows\Modules\mullvad.Module.InstalledApplications.dll"
          SkipUnchangedFiles="false" ContinueOnError="true" />
  </Target>

</Project>
