<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>mullvad.Module.Keylogger</AssemblyName>
    <RootNamespace>mullvad.Module.Keylogger</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <Target Name="CopyToModules" AfterTargets="Build">
    <MakeDir Directories="..\..\mullvad\bin\$(Configuration)\net8.0-windows\Modules" ContinueOnError="true" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
          DestinationFiles="..\..\mullvad\bin\$(Configuration)\net8.0-windows\Modules\mullvad.Module.Keylogger.dll"
          SkipUnchangedFiles="true" ContinueOnError="true" />
    <MakeDir Directories="..\build\Alpha\Modules" ContinueOnError="true" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
          DestinationFiles="..\build\Alpha\Modules\mullvad.Module.Keylogger.dll"
          SkipUnchangedFiles="true" ContinueOnError="true" />
  </Target>

</Project>
