<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>RemoteDesktop</AssemblyName>
    <RootNamespace>mullvad.Module.RemoteDesktop</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>
  <Target Name="CopyToModules" AfterTargets="Build">
    <MakeDir Directories="..\..\mullvad\bin\$(Configuration)\net8.0-windows\Modules" ContinueOnError="true" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
          DestinationFiles="..\..\mullvad\bin\$(Configuration)\net8.0-windows\Modules\mullvad.Module.RemoteDesktop.dll"
          SkipUnchangedFiles="true" ContinueOnError="true" />
  </Target>
</Project>
